name: senkom_news_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-262.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # webview_flutter: ^4.13.0
  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
